# Generated by Django 5.0.3 on 2024-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageCard', models.ImageField(upload_to='img/')),
                ('description', models.TextField(blank=True, null=True)),
                ('titleCard', models.CharField(max_length=200)),
                ('priceCard', models.IntegerField(max_length=7)),
            ],
        ),
    ]
